import * as React from "react";
import { cn } from "@/lib/utils";

export function Button({ className, variant = "primary", size = "default", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger"; size?: "default" | "sm" | "icon" }) {
  return <button className={cn("inline-flex items-center justify-center gap-2 rounded-lg font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)] disabled:pointer-events-none disabled:opacity-50", variant === "primary" && "bg-[var(--accent)] text-white hover:bg-[var(--accent-strong)]", variant === "secondary" && "border border-[var(--border)] bg-[var(--surface)] hover:bg-[var(--surface-muted)]", variant === "ghost" && "hover:bg-[var(--surface-muted)]", variant === "danger" && "bg-red-600 text-white hover:bg-red-700", size === "default" && "h-10 px-4 text-sm", size === "sm" && "h-8 px-3 text-xs", size === "icon" && "h-9 w-9", className)} {...props} />;
}

export function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("rounded-xl border border-[var(--border)] bg-[var(--surface)] shadow-[0_1px_2px_rgba(20,31,25,.03)]", className)} {...props} />; }
export function CardHeader({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("flex items-start justify-between gap-4 p-5 pb-3", className)} {...props} />; }
export function CardContent({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("p-5 pt-2", className)} {...props} />; }
export function Badge({ children, tone = "neutral", className }: { children: React.ReactNode; tone?: "success" | "warning" | "danger" | "neutral" | "info"; className?: string }) { return <span className={cn("inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium", tone === "success" && "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300", tone === "warning" && "bg-amber-500/12 text-amber-700 dark:text-amber-300", tone === "danger" && "bg-red-500/10 text-red-700 dark:text-red-300", tone === "info" && "bg-blue-500/10 text-blue-700 dark:text-blue-300", tone === "neutral" && "bg-[var(--surface-muted)] text-[var(--muted)]", className)}>{children}</span>; }
export function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={cn("h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 text-sm outline-none placeholder:text-[var(--muted)] focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--accent-soft)]", props.className)} />; }
export function Select(props: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className={cn("h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 text-sm outline-none focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--accent-soft)]", props.className)} />; }
export function Label({ className, ...props }: React.LabelHTMLAttributes<HTMLLabelElement>) { return <label className={cn("mb-1.5 block text-sm font-medium", className)} {...props} />; }
export function Skeleton({ className }: { className?: string }) { return <div className={cn("animate-pulse rounded-lg bg-[var(--surface-muted)]", className)} />; }
export function EmptyState({ icon, title, body, action }: { icon: React.ReactNode; title: string; body: string; action?: React.ReactNode }) { return <div className="flex min-h-64 flex-col items-center justify-center p-8 text-center"><div className="mb-4 rounded-xl bg-[var(--surface-muted)] p-3 text-[var(--muted)]">{icon}</div><h3 className="font-semibold">{title}</h3><p className="mt-1 max-w-sm text-sm text-[var(--muted)]">{body}</p>{action && <div className="mt-5">{action}</div>}</div>; }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: React.ReactNode }) { return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div>{eyebrow && <p className="mb-1 text-xs font-semibold uppercase tracking-[.16em] text-[var(--accent)]">{eyebrow}</p>}<h1 className="text-2xl font-semibold tracking-[-.03em] sm:text-3xl">{title}</h1><p className="mt-1.5 max-w-2xl text-sm leading-6 text-[var(--muted)]">{description}</p></div>{action}</div>; }
export function StatusDot({ status }: { status: string }) { const active = ["online", "active"].includes(status); const warning = status === "never"; return <span className={cn("h-2 w-2 rounded-full", active ? "bg-emerald-500" : warning ? "bg-amber-500" : "bg-red-500")} />; }
